apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-aovivoesporte
  namespace: frontend
  labels:
    environment: dev
    team: infra
    owner: eduardo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-aovivoesporte
      version: v1
  template:
    metadata:
      labels:
        app: frontend-aovivoesporte
        version: v1
    spec:
      containers:
      imagePullSecrets:
      - name: dockerhub-secret
        image: eduardoananias/aovivoesportes-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
