apiVersion: v1
kind: Service
metadata:
  name: frontend-aovivoesporte
  namespace: frontend
  labels:
    environment: dev
    team: infra
spec:
  selector:
    app: frontend-aovivoesporte
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
