apiVersion: v1
kind: Service
metadata:
  name: {{.values.app.name}}
  namespace: {{.values.app.namespace}}
  labels:
    environment: dev
    team: infra
spec:
  selector:
    app: {{.values.app.name}}
  ports:
    - port: {{.values.service.port}}
      targetPort: {{.values.service.port}}
  type: {{.values.service.type}}
